### PR TITLE
Added iMessage instructions

### PR DESCRIPTION
**Pull request by Porco-Rosso**
Hi, I've added clearer instructions on how to enable iMessage/Facetime/iCloud. The old guide that was linked, had a lot of confusing information and unnecessary steps.
If you rather not have instructions maintained as part of the repo, I suggest you at least change the linked guide to the following: [https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/post-install/post-install/iservices](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/post-install/post-install/iservices)

### CODE REVIEW

**Comment by tylernguyen** [comment]
Thank you so much for your updated instructions! It's definitely better than what I had before.

**Comment by jeed2424** [comment]
Hi, do you have the new link for it? I’ll look for it and update it here if I find it, but it seems to have moved somewhere else (you can read the message on the website)

**Comment by tylernguyen** [comment]
@jeed2424 It will be in my next commit, which include OC upgrades and others. Coming in the next 2 to 3 days.

**Comment by Porco-Rosso** [comment]
@jeed2424 Meanwhile you can find it here: https://dortania.github.io/OpenCore-Desktop-Guide/post-install/iservices.html

**Pull request merged**
